
# Frontend
services:
  frontend_base:
    profiles:
      - template
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_API_URL: /api
    volumes:
      - frontend_data:/app
      - frontend_node_modules:/app/node_modules
    restart: unless-stopped
    networks:
      - alpacaparty_net

  frontend:
    profiles:
      - dev
    extends: frontend_base
    container_name: frontend
    depends_on:
      backend:
        condition: service_started

  frontend_test:
    profiles:
      - test
    extends: frontend_base
    container_name: frontend_test
    depends_on:
      backend_test:
        condition: service_started
