# Docker Compose — Development
# @owner ValGSgit
# @issue https://github.com/ValGSgit/AlpacaParty/issues/3

# include each service
include:
  - ./backend/compose.yaml
  - ./e2e/compose.yaml
  - ./frontend/compose.yaml
  - ./nginx/compose.yaml
  - ./database/compose.yaml
  - ./vault/compose.yaml
  - ./scripts/compose.yaml


volumes:
  pg_data:
  vault_data:
    driver: local
  vault_keys:
    driver: local
  stress_test_results:
    driver: local
  backend_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend
  frontend_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./frontend
  ssl:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./ssl


networks:
  alpacaparty_net:
    name: alpacaparty_net
