/**
 * Auth Routes Integration Tests
 */
import {
  describe,
  test,
  expect,
  beforeEach,
  afterAll,
  beforeAll,
} from "@jest/globals";
import supertest from "supertest";
import prisma from "#config/prisma.js";
import AuthService from "#services/authService.js";
import { createTestApp } from "../helpers/createApp.js";

let app;
let request;
let validToken;
let authPasswordHash;

// #region Setup

beforeAll(async () => {
  authPasswordHash = await AuthService.hashPassword("TestPassword1234");
});

beforeEach(async () => {
  app = await createTestApp();
  request = supertest(app);

  // Create the actual record in the test DB
  await prisma.user.deleteMany({
    where: {
      username: {
        in: ["testUser", "authed"],
      },
    },
  });

  const user = await prisma.user.create({
    data: {
      username: "authed",
      email: "a@b.com",
      avatar: "/avatars/default.svg",
      status: "online",
      bio: "something",
      userAuth: {
        create: {
          passwordHash: authPasswordHash,
        },
      },
    },
  });

  // Sign the token with the REAL ID generated by Prisma
  validToken = AuthService.generateAccessToken({
    id: user.id,
    username: user.username,
    is_admin: false,
  });
});

afterAll(async () => {
  await prisma.$disconnect();
});

// #endregion

// #region Tests

describe("POST /api/auth/register", () => {
  test("400 for missing username", async () => {
    const res = await request
      .post("/api/auth/register")
      .send({ email: "a@b.com", password: "ValidPass1" });
    expect(res.status).toBe(400);
  });

  test("400 for missing email", async () => {
    const res = await request
      .post("/api/auth/register")
      .send({ username: "FickDieHenne", password: "ValidPass1" });
    expect(res.status).toBe(400);
  });

  test("409 when username already exists", async () => {
    const res = await request.post("/api/auth/register").send({
      username: "authed", // before each creates this
      email: "new@example.com",
      password: "ValidPass1",
    });

    expect(res.status).toBe(409);
    console.log(res.body);
    expect(res.body.error.message).toMatch(/user/i); // i == case insesitive
    expect(res.body.error.message).toMatch(/taken/i);
  });

  test("409 when email already exists", async () => {
    const res = await request.post("/api/auth/register").send({
      username: "TestUsername",
      email: "a@b.com", // before each creates this
      password: "ValidPass1",
    });

    expect(res.status).toBe(409);
    expect(res.body.error.message).toMatch(/email/i); // i == case insesitive
    expect(res.body.error.message).toMatch(/exists/i);
  });

  test("201 on successful registration", async () => {
    const res = await request.post("/api/auth/register").send({
      username: "newuser",
      email: "new@example.com",
      password: "ValidPass1",
    });

    expect(res.status).toBe(201);
    expect(res.body.accessToken).toBeDefined();
    expect(res.body.refreshToken).toBeDefined();
  });
});

describe("POST /api/auth/login", () => {
  test("400 for missing username", async () => {
    const res = await request
      .post("/api/auth/login")
      .send({ username: "", password: "TestPassword1234" });
    expect(res.status).toBe(400);
    expect(res.body.error.message).toMatch(/username/i);
  });

  test("400 for missing password", async () => {
    const res = await request
      .post("/api/auth/login")
      .send({ username: "user" });
    expect(res.status).toBe(400);
    expect(res.body.error.message).toMatch(/password/i);
  });

  test("401 for unknown user", async () => {
    const res = await request
      .post("/api/auth/login")
      .send({ username: "ghost", password: "ValidPass1" });
    expect(res.status).toBe(401);
    expect(res.body.error.message).toMatch(/invalid/i);
  });

  test("200 for valid credentials", async () => {
    const res = await request
      .post("/api/auth/login")
      .send({ username: "authed", password: "TestPassword1234" });
    expect(res.status).toBe(200);
    expect(res.body.accessToken).toBeDefined();
    expect(res.body.user.isOnline).toBe(true);
  });
});

describe("POST /api/auth/refresh", () => {
  test("401 for invalid refresh token", async () => {
    const res = await request
      .post("/api/auth/refresh")
      .send({ refreshToken: "bad-token" });
    expect(res.status).toBe(401);
  });

  test("200 for valid refresh token", async () => {
    var refreshToken;
    //login to get refresh token
    {
      const res = await request
        .post("/api/auth/login")
        .send({ username: "authed", password: "TestPassword1234" });
      expect(res.status).toBe(200);
      expect(res.body.refreshToken).toBeDefined();
      refreshToken = res.body.refreshToken;
    }

    const res = await request.post("/api/auth/refresh").send({ refreshToken });
    expect(res.status).toBe(200);
    expect(res.body.accessToken).toBeDefined();
  });
});

describe("GET /api/auth/me", () => {
  test("401 without token", async () => {
    const res = await request.get("/api/auth/me");
    console.log(res.body);
    expect(res.status).toBe(401);
    expect(res.body.error.message).toMatch(/authentication/i);
    expect(res.body.error.message).toMatch(/required/i);
  });

  test("200 with valid token", async () => {
    const res = await request
      .get("/api/auth/me")
      .set("Authorization", `Bearer ${validToken}`);
    expect(res.status).toBe(200);
    expect(res.body.user.username).toBe("authed");
  });
});

//#endregion
