/**
 * User Routes Integration Tests
 */
import {
  describe,
  test,
  expect,
  beforeEach,
  afterAll,
  beforeAll,
} from "@jest/globals";
import supertest from "supertest";
import prisma from "#config/prisma.js";
import AuthService from "#services/authService.js";
import { createTestApp } from "../helpers/createApp.js";
import { createTestUsers } from "../helpers/createTestUsers.js";

let app;
let request;
let validToken;
let authPasswordHash;

// #region Setup

beforeAll(async () => {
  authPasswordHash = await AuthService.hashPassword("TestPassword1234");
});

beforeEach(async () => {
  app = await createTestApp();
  request = supertest(app);

  // Create the actual record in the test DB
  await prisma.user.deleteMany({
    where: {
      username: {
        in: ["testUser", "authed"],
      },
    },
  });

  const user = await prisma.user.create({
    data: {
      username: "authed",
      email: "a@b.com",
      avatar: "/avatars/default.svg",
      status: "online",
      bio: "something",
      userAuth: {
        create: {
          passwordHash: authPasswordHash,
        },
      },
    },
  });

  // Sign the token with the REAL ID generated by Prisma
  validToken = AuthService.generateAccessToken({
    id: user.id,
    username: user.username,
    is_admin: false,
  });
});

afterAll(async () => {
  // Disconnect Prisma so Jest can exit properly
  await prisma.$disconnect();
});

// #endregion

// #region Tests

// ────────────────────────────────────────────────────────────────
// GET /api/users/me
// ────────────────────────────────────────────────────────────────
describe("GET /api/users/me", () => {
  test("200 — returns current user", async () => {
    const res = await request
      .get("/api/users/me")
      .set("Authorization", `Bearer ${validToken}`);

    expect(res.status).toBe(200);
    expect(res.body.user.username).toBe("authed");
  });

  test("401 — without token", async () => {
    const res = await request.get("/api/users/me");
    expect(res.status).toBe(401);
  });
});

// ────────────────────────────────────────────────────────────────
// PUT /api/users/me
// ────────────────────────────────────────────────────────────────
describe("PUT /api/users/me", () => {
  test("200 — update profile data", async () => {
    const testUserUpdate = {
      username: "testUser",
      email: "test@gmail.com",
      bio: "testBio",
      status: "testStatus",
      avatar: "testAvatar",
    };

    const res = await request
      .put("/api/users/me")
      .set("Authorization", `Bearer ${validToken}`)
      .send(testUserUpdate);

    expect(res.status).toBe(200);
    expect(res.body.user.username).toBe(testUserUpdate.username);
    expect(res.body.user.email).toBe(testUserUpdate.email);
    expect(res.body.user.bio).toBe(testUserUpdate.bio);
    expect(res.body.user.status).toBe(testUserUpdate.status);
    expect(res.body.user.avatar).toBe(testUserUpdate.avatar);
  });

  test("401 — without token", async () => {
    const res = await request.get("/api/users/me/profile");
    expect(res.status).toBe(401);
  });
});

// ────────────────────────────────────────────────────────────────
// PUT /api/users/me/password
// ────────────────────────────────────────────────────────────────
const updatePasswordRequest = async (newPw) => {
  return await request
    .put("/api/users/me/password")
    .set("Authorization", `Bearer ${validToken}`)
    .send({
      currentPassword: "TestPassword1234",
      newPassword: newPw,
    });
};

describe("PUT /api/users/me/password", () => {
  test("200 — update password", async () => {
    const res = await updatePasswordRequest("NewTestPassword1234");
    expect(res.status).toBe(200);
  });

  test("400 — password: too short", async () => {
    const res = await updatePasswordRequest("len");
    expect(res.body.errors.newPassword).toContain("characters");
    expect(res.status).toBe(400);
  });

  test("400 — password: too long", async () => {
    const res = await updatePasswordRequest("A1" + "a".repeat(50));
    expect(res.body.errors.newPassword).toContain("characters");
    expect(res.status).toBe(400);
  });

  test("400 — password: no uppercase", async () => {
    const res = await updatePasswordRequest("nouppercase");
    expect(res.body.errors.newPassword).toContain("uppercase");
    expect(res.status).toBe(400);
  });

  test("400 — password: no lowercase", async () => {
    const res = await updatePasswordRequest("NOLOWERCASE");
    expect(res.body.errors.newPassword).toContain("lowercase");
    expect(res.status).toBe(400);
  });

  test("400 — password: no number", async () => {
    const res = await updatePasswordRequest("NoNumber");
    expect(res.body.errors.newPassword).toContain("number");
    expect(res.status).toBe(400);
  });
});

// ────────────────────────────────────────────────────────────────
// GET /api/users
// ────────────────────────────────────────────────────────────────
describe("GET /api/users", () => {
  //Seed database with users
  beforeAll(async () => {
    await createTestUsers(10);
  });

  test("200 — list users first page", async () => {
    const page = 1;
    const pageSize = 2;
    const res = await request
      .get(`/api/users?page=${page}&pageSize=${pageSize}`)
      .set("Authorization", `Bearer ${validToken}`);

    const users = res.body.users;
    expect(users.length).toBe(2);
    expect(res.body.currentPage).toBe(1);
    expect(res.body.pageSize).toBe(2);
    expect(res.status).toBe(200);
  });

  test("200 — list users second page", async () => {
    const page = 2;
    const pageSize = 3;
    const res = await request
      .get(`/api/users?page=${page}&pageSize=${pageSize}`)
      .set("Authorization", `Bearer ${validToken}`);

    const users = res.body.users;
    expect(users.length).toBe(3);
    expect(res.body.currentPage).toBe(2);
    expect(res.body.pageSize).toBe(3);
    expect(res.status).toBe(200);
  });
});

// ────────────────────────────────────────────────────────────────
// GET /api/users/:id
// ────────────────────────────────────────────────────────────────
describe("GET /api/users/:id", () => {
  //Seed database with users
  var createdUsers;
  beforeAll(async () => {
    createdUsers = await createTestUsers(3);
  });

  test("200 — get user 1", async () => {
    const res = await request
      .get(`/api/users/${createdUsers[0].id}`)
      .set("Authorization", `Bearer ${validToken}`);

    const user = res.body.user;
    expect(res.status).toBe(200);
    expect(user.username).toBeDefined();
    expect(user.id).toBe(createdUsers[0].id);
  });

  test("200 — get user 2", async () => {
    const res = await request
      .get(`/api/users/${createdUsers[1].id}`)
      .set("Authorization", `Bearer ${validToken}`);

    const user = res.body.user;
    expect(res.status).toBe(200);
    expect(user.username).toBeDefined();
    expect(user.id).toBe(createdUsers[1].id);
  });
});

// #endregion
