/**
 * User Routes Integration Tests
 */
import {
  describe,
  test,
  expect,
  beforeEach,
  afterAll,
  beforeAll,
} from "@jest/globals";
import supertest from "supertest";
import prisma from "#lib/prisma.js";
import AuthService from "#services/authService.js";
import { createTestApp } from "../helpers/createApp.js";
import { createTestUsers } from "../helpers/createTestUsers.js";

let app;
let request;
let validToken;
let authPasswordHash;

beforeAll(async () => {
  authPasswordHash = await AuthService.hashPassword("TestPassword1234");
});

beforeEach(async () => {
  app = await createTestApp();
  request = supertest(app);

  // Create the actual record in the test DB
  await prisma.user.deleteMany({
    where: {
      username: {
        in: ["testUser", "authed"],
      },
    },
  });

  const user = await prisma.user.create({
    data: {
      username: "authed",
      email: "a@b.com",
      avatar: "/avatars/default.svg",
      status: "online",
      bio: "something",
      userAuth: {
        create: {
          passwordHash: authPasswordHash,
        },
      },
    },
  });

  // Sign the token with the REAL ID generated by Prisma
  validToken = AuthService.generateAccessToken({
    id: user.id,
    username: user.username,
    is_admin: false,
  });
});

afterAll(async () => {
  // Disconnect Prisma so Jest can exit properly
  await prisma.$disconnect();
});

// ────────────────────────────────────────────────────────────────
// GET /api/users/me
// ────────────────────────────────────────────────────────────────
describe("GET /api/users/me", () => {
  test("200 — returns current user", async () => {
    const res = await request
      .get("/api/users/me")
      .set("Authorization", `Bearer ${validToken}`);

    expect(res.status).toBe(200);
    expect(res.body.user.username).toBe("authed");
  });

  test("401 — without token", async () => {
    const res = await request.get("/api/users/me");
    expect(res.status).toBe(401);
  });
});

// ────────────────────────────────────────────────────────────────
// PUT /api/users/me
// ────────────────────────────────────────────────────────────────
describe("PUT /api/users/me", () => {
  test("200 — update profile data", async () => {
    const testUserUpdate = {
      username: "testUser",
      email: "test@gmail.com",
      bio: "testBio",
      status: "testStatus",
      avatar: "testAvatar",
    };

    const res = await request
      .put("/api/users/me")
      .set("Authorization", `Bearer ${validToken}`)
      .send(testUserUpdate);

    expect(res.status).toBe(200);
    expect(res.body.user.username).toBe(testUserUpdate.username);
    expect(res.body.user.email).toBe(testUserUpdate.email);
    expect(res.body.user.bio).toBe(testUserUpdate.bio);
    expect(res.body.user.status).toBe(testUserUpdate.status);
    expect(res.body.user.avatar).toBe(testUserUpdate.avatar);
  });

  test("401 — without token", async () => {
    const res = await request.get("/api/users/me/profile");
    expect(res.status).toBe(401);
  });
});

// ────────────────────────────────────────────────────────────────
// PUT /api/users/me/password
// ────────────────────────────────────────────────────────────────
const updatePasswordRequest = async (newPw) => {
  return await request
    .put("/api/users/me/password")
    .set("Authorization", `Bearer ${validToken}`)
    .send({
      currentPassword: "TestPassword1234",
      newPassword: newPw,
    });
};

describe("PUT /api/users/me/password", () => {
  test("200 — update password", async () => {
    const res = await updatePasswordRequest("NewTestPassword1234");
    expect(res.status).toBe(200);
  });

  test("400 — password: too short", async () => {
    const res = await updatePasswordRequest("len");
    expect(res.body.errors.newPassword).toContain("characters");
    expect(res.status).toBe(400);
  });

  test("400 — password: too long", async () => {
    const res = await updatePasswordRequest("A1" + "a".repeat(50));
    expect(res.body.errors.newPassword).toContain("characters");
    expect(res.status).toBe(400);
  });

  test("400 — password: no uppercase", async () => {
    const res = await updatePasswordRequest("nouppercase");
    expect(res.body.errors.newPassword).toContain("uppercase");
    expect(res.status).toBe(400);
  });

  test("400 — password: no lowercase", async () => {
    const res = await updatePasswordRequest("NOLOWERCASE");
    expect(res.body.errors.newPassword).toContain("lowercase");
    expect(res.status).toBe(400);
  });

  test("400 — password: no number", async () => {
    const res = await updatePasswordRequest("NoNumber");
    expect(res.body.errors.newPassword).toContain("number");
    expect(res.status).toBe(400);
  });
});

// ────────────────────────────────────────────────────────────────
// GET /api/users
// ────────────────────────────────────────────────────────────────
describe("GET /api/users", () => {
  //Seed database with users
  beforeAll(async () => {
    await createTestUsers(10);
  });

  test("200 — list users first page", async () => {
    const page = 1;
    const pageSize = 2;
    const res = await request
      .get(`/api/users?page=${page}&pageSize=${pageSize}`)
      .set("Authorization", `Bearer ${validToken}`);

    const users = res.body.users;
    expect(users.length).toBe(2);
    expect(res.body.currentPage).toBe(1);
    expect(res.body.pageSize).toBe(2);
    expect(res.status).toBe(200);
  });

  test("200 — list users second page", async () => {
    const page = 2;
    const pageSize = 3;
    const res = await request
      .get(`/api/users?page=${page}&pageSize=${pageSize}`)
      .set("Authorization", `Bearer ${validToken}`);

    const users = res.body.users;
    expect(users.length).toBe(3);
    expect(res.body.currentPage).toBe(2);
    expect(res.body.pageSize).toBe(3);
    expect(res.status).toBe(200);
  });
});

// // ────────────────────────────────────────────────────────────────
// // PUT /api/users/me
// // ────────────────────────────────────────────────────────────────
// describe('PUT /api/users/me', () => {
//   test('200 — update bio', async () => {
//     mockAuth();
//     mockQuery.mockResolvedValueOnce({
//       rows: [{ ...authUser, bio: 'New bio' }],
//     });

//     const res = await request
//       .put('/api/users/me')
//       .set('Authorization', `Bearer ${validToken}`)
//       .send({ bio: 'New bio' });

//     expect(res.status).toBe(200);
//     expect(res.body.user.bio).toBe('New bio');
//   });

//   test('200 — update username (available)', async () => {
//     mockAuth();
//     mockQuery.mockResolvedValueOnce({ rows: [] }); // findByUsername → available
//     mockQuery.mockResolvedValueOnce({ rows: [{ ...authUser, username: 'newname' }] }); // update

//     const res = await request
//       .put('/api/users/me')
//       .set('Authorization', `Bearer ${validToken}`)
//       .send({ username: 'newname' });

//     expect(res.status).toBe(200);
//   });

//   test('400 — username too short', async () => {
//     mockAuth();
//     const res = await request
//       .put('/api/users/me')
//       .set('Authorization', `Bearer ${validToken}`)
//       .send({ username: 'ab' });

//     expect(res.status).toBe(400);
//   });

//   test('400 — username invalid chars', async () => {
//     mockAuth();
//     const res = await request
//       .put('/api/users/me')
//       .set('Authorization', `Bearer ${validToken}`)
//       .send({ username: 'bad user!' });

//     expect(res.status).toBe(400);
//   });

//   test('409 — username taken', async () => {
//     mockAuth();
//     mockQuery.mockResolvedValueOnce({ rows: [{ id: 99, username: 'taken' }] }); // findByUsername → exists

//     const res = await request
//       .put('/api/users/me')
//       .set('Authorization', `Bearer ${validToken}`)
//       .send({ username: 'taken' });

//     expect(res.status).toBe(409);
//   });

//   test('409 — email taken', async () => {
//     mockAuth();
//     mockQuery.mockResolvedValueOnce({ rows: [{ id: 99, email: 'taken@x.com' }] }); // findByEmail → exists

//     const res = await request
//       .put('/api/users/me')
//       .set('Authorization', `Bearer ${validToken}`)
//       .send({ email: 'taken@x.com' });

//     expect(res.status).toBe(409);
//   });

//   test('200 — empty body returns current user', async () => {
//     mockAuth();
//     // User.update with no sets → calls findById
//     mockQuery.mockResolvedValueOnce({ rows: [authUser] });

//     const res = await request
//       .put('/api/users/me')
//       .set('Authorization', `Bearer ${validToken}`)
//       .send({});

//     expect(res.status).toBe(200);
//   });
// });

// // ────────────────────────────────────────────────────────────────
// // PUT /api/users/me/password
// // ────────────────────────────────────────────────────────────────
// describe("PUT /api/users/me/password", () => {
//   test("200 — password changed successfully", async () => {
//     const currentHash = await AuthService.hashPassword("OldPass1");
//     mockAuth();
//     mockQuery.mockResolvedValueOnce({
//       rows: [{ ...authUser, password_hash: currentHash }],
//     }); // findByIdWithPassword
//     mockQuery.mockResolvedValueOnce({ rows: [] }); // updatePassword

//     const res = await request
//       .put("/api/users/me/password")
//       .set("Authorization", `Bearer ${validToken}`)
//       .send({ currentPassword: "OldPass1", newPassword: "NewPass1" });

//     expect(res.status).toBe(200);
//     expect(res.body.message).toBe("Password updated");
//   });

//   test("400 — missing fields", async () => {
//     mockAuth();
//     const res = await request
//       .put("/api/users/me/password")
//       .set("Authorization", `Bearer ${validToken}`)
//       .send({ currentPassword: "Old1" });

//     expect(res.status).toBe(400);
//   });

//   test("401 — current password incorrect", async () => {
//     const hash = await AuthService.hashPassword("RealPass1");
//     mockAuth();
//     mockQuery.mockResolvedValueOnce({
//       rows: [{ ...authUser, password_hash: hash }],
//     });

//     const res = await request
//       .put("/api/users/me/password")
//       .set("Authorization", `Bearer ${validToken}`)
//       .send({ currentPassword: "WrongPass1", newPassword: "NewPass1" });

//     expect(res.status).toBe(401);
//   });

//   test("400 — new password too weak", async () => {
//     const hash = await AuthService.hashPassword("OldPass1");
//     mockAuth();
//     mockQuery.mockResolvedValueOnce({
//       rows: [{ ...authUser, password_hash: hash }],
//     });

//     const res = await request
//       .put("/api/users/me/password")
//       .set("Authorization", `Bearer ${validToken}`)
//       .send({ currentPassword: "OldPass1", newPassword: "weak" });

//     expect(res.status).toBe(400);
//   });
// });

// // ────────────────────────────────────────────────────────────────
// // GET /api/users/:id
// // ────────────────────────────────────────────────────────────────
// describe('GET /api/users/:id', () => {
//   test('200 — returns user by id', async () => {
//     mockAuth();
//     mockQuery.mockResolvedValueOnce({ rows: [{ id: 2, username: 'other', bio: 'hi', is_public: true }] });

//     const res = await request.get('/api/users/2').set('Authorization', `Bearer ${validToken}`);
//     expect(res.status).toBe(200);
//     expect(res.body.user.username).toBe('other');
//   });

//   test('404 — user not found', async () => {
//     mockAuth();
//     mockQuery.mockResolvedValueOnce({ rows: [] });

//     const res = await request.get('/api/users/999').set('Authorization', `Bearer ${validToken}`);
//     expect(res.status).toBe(404);
//   });
// });

// // ────────────────────────────────────────────────────────────────
// // GET /api/users
// // ────────────────────────────────────────────────────────────────
// describe('GET /api/users', () => {
//   test('200 — returns list of users', async () => {
//     mockAuth();
//     mockQuery.mockResolvedValueOnce({
//       rows: [
//         { id: 1, username: 'user1', is_public: true },
//         { id: 2, username: 'user2', is_public: true },
//       ],
//     });

//     const res = await request.get('/api/users').set('Authorization', `Bearer ${validToken}`);
//     expect(res.status).toBe(200);
//     expect(res.body.users).toHaveLength(2);
//   });

//   test('200 — search users', async () => {
//     mockAuth();
//     mockQuery.mockResolvedValueOnce({
//       rows: [{ id: 1, username: 'tester', avatar: null, is_online: true }],
//     });

//     const res = await request
//       .get('/api/users?search=test')
//       .set('Authorization', `Bearer ${validToken}`);

//     expect(res.status).toBe(200);
//     expect(res.body.users).toHaveLength(1);
//   });

//   test('200 — pagination params', async () => {
//     mockAuth();
//     mockQuery.mockResolvedValueOnce({ rows: [] });

//     const res = await request
//       .get('/api/users?limit=10&offset=20')
//       .set('Authorization', `Bearer ${validToken}`);

//     expect(res.status).toBe(200);
//   });
// });
