# nginx reverse proxy
services:
  nginx_base:
    profiles:
      - template
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:443"
      - "8080:80"
    volumes:
      - ssl:/etc/nginx/conf/ssl
      - ./conf/nginx.conf:/etc/nginx/templates/conf.d/default.conf.template:ro
    restart: always
    networks:
      - alpacaparty_net
    healthcheck:
      test: ["CMD-SHELL", "nginx -t"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    profiles:
      - dev
    extends: nginx_base
    container_name: nginx
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started

  nginx_test:
    profiles:
      - test
    extends: nginx_base
    container_name: nginx_test
    depends_on:
      backend_test:
        condition: service_started
